config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  post '/reviews/:id', to:'reviews#update'
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :users
  resources :lectures
  resources :reviews
end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  has_many :reviews
  validates :display_name, presence: true, uniqueness: true
  validates :year, numericality: {less_than: 2015}, presence: true
  validates :semester, inclusion: { in: %w(Fall Spring Summer),
    message: "Semester must be Fall, Spring or Summer" }, allow_nil: false
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :lecture
  belongs_to :reviewer, class_name: "User"
  belongs_to :person_reviewed, class_name: "User"
  validates :rating, presence: true, length: {minimum: 0, maximum: 5}
  validates :description, presence: true, length: {maximum: 500} # maximum 500 chars
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :given_reviews, class_name: "Review", foreign_key: "reviewer_id"
  has_many :received_reviews, class_name: "Review", foreign_key: "person_reviewed_id"
  validates :email, format: { with: /\A\w+@berkeley.edu\z/, message: ": only @berkeley.edu emails allowed at this time"}
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(name:auth.extra.raw_info.name,
                            provider:auth.provider,
                            uid:auth.uid,
                            email:auth.info.email,
                            password:Devise.friendly_token[0,20],
                          )
      end    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  def index
    @lectures = Lecture.all
  end

  def show
    @lecture = Lecture.find(params[:id])
  end

  def create
    @lecture = Lecture.new(lecture_params)
    @lecture.display_name = @lecture.name + " " + @lecture.semester + " " + @lecture.year.to_s
    @lecture.save
    if not @lecture.errors.full_messages.empty?
      flash[:error] = @lecture.errors.full_messages.to_sentence
      redirect_to new_lecture_path
    else
      redirect_to lectures_path
    end
  end

  def new
    render 'new'
  end


  private

  def lecture_params
    params.require(:lecture).permit(:name, :semester, :year)
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController   
def facebook     
     @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)      
     if @user.persisted?       
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def show
    @review = Review.find(params[:id])
    @reviewer = User.find(@review.reviewer_id)
    @person_being_reviewed = User.find(@review.person_reviewed_id)
  end

  def edit
    @users = User.all
    @lectures = Lecture.all
    @review = Review.find(params[:id])
    puts "====="
    puts @review.lecture_name
  end

  def new
    @users = User.all
    @lectures = Lecture.all
  end

  def update
    @review = Review.find(params[:id])
    @review.rating = update_review_rating
    @review.description = update_review_description
    if not @review.errors.full_messages.empty?
      flash[:error] = @review.errors.full_messages.to_sentence
      redirect_to edit_review_path
    elsif @review.rating < 0 or @review.rating > 5
      flash[:error] = "Rating must be in the range 0-5"
      redirect_to edit_review_path
    else
      @review.save
      redirect_to lectures_path
    end

  end

  def create
    @review = Review.new(review_params)
    name = @review.person_being_reviewed
    @person_reviewed = User.where(name: name).first
    @review.person_reviewed_id = @person_reviewed.id

    lecture = @review.lecture_name
    @lectue_reviewed = Lecture.where(display_name: lecture).first
    @review.lecture_id = @lectue_reviewed.id

    @review.reviewer_id = current_user[:id]

    if not @review.errors.full_messages.empty?
      flash[:error] = @review.errors.full_messages.to_sentence
      redirect_to new_review_path
    elsif @review.rating < 0 or @review.rating > 5
      flash[:error] = "Rating must be in the range 0-5"
      redirect_to new_review_path
    else
      @review.save
      redirect_to lectures_path
    end
  end

  private

  def review_params
    params.require(:review).permit(:description, :rating, :person_being_reviewed, :lecture_name)
  end

  def update_review_description
    params.require(:review).permit(:description)[:description]
  end

  def update_review_rating
    puts "========update======"
    puts params[:review][:rating]
    params.require(:review).permit(:rating)[:rating]
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @user_reviews = Review.where(person_reviewed_id: @user.id)
    @average_rating = average_rating(@user, false)
    @average_given_rating = average_rating(@user, true)
  end

  def average_rating(user, given)
  	if given
  	  reviews = Review.where(reviewer: @user).select('rating')
  	else
  	  reviews = Review.where(person_reviewed: @user).select('rating')
  	end
  	if reviews.length == 0
  	  return ''
  	end
  	arr = Array.new
  	for i in 0..(reviews.count - 1)
      arr.append(reviews[i]['rating'])
    end
    average_rating = arr.inject{ |sum, el| sum + el }.to_f / arr.size
    return average_rating.to_s[0..2]
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/home/index.html.erb
<div class="jumbotron">
        <h1>Find a Partner That Rocks</h1>
        <p class="lead">Discover and Rate Partners. Ace Your Projects.</p>
        <p>
        	<a class="btn btn-lg btn-success" href="users/sign_up" role="button">Sign up today</a>
        </p>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
  <li><%= link_to 'Lectures', lectures_path %></li>
  <li><%= link_to 'Create a Review', new_review_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
  <li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Partner Rank" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Partner" %>">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
  <footer class="footer">
      <div class="container">
        <p class="text-muted">&copy; 2014 Voges, Flynn, Tan, Radding</p>
      </div>
    </footer>
</html>

app/views/lectures/_lecture.html.erb
<td><%= link_to lecture.display_name, lecture %></td>

app/views/lectures/index.html.erb
<div class="container">
  <div class="row">
    <h3>Lectures</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @lectures.each do |lecture| %>
            <tr>
              <%= render lecture %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= button_to "Create new lecture", new_lecture_path, :class => "button medium", :method => :get %>
  </div>
</div>

app/views/lectures/new.html.erb
<div class='container'>
  <h1 class='text-center'>Add a New Lecture!</h1>
  <br>
  <div class='row'>
    <div class='col-md-3'></div>
    <div class='col-md-6'>
      <%= simple_form_for(Lecture.new, url: {action: "create"}) do |l| %>
        <%= l.input :name %>
        <%= l.input :semester, collection: ["Fall", "Spring"], prompt: "Select Semester" %>
        <%= l.input :year, collection: (Time.new.year-5)..(Time.new.year+2), prompt: "Select Year" %>
        <br>
        <%= l.button :submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/lectures/show.html.erb
<h3><%= @lecture.name + " " + @lecture.semester + " " + @lecture.year.to_s %></h3>
<div class="create-button"> 
  <%= link_to "Create a review!", new_review_path %>
</div>
<% if @lecture.reviews.any? %>
  <div id="student-list"> <h4>Students:</h4> 
    <ul>
      <% user_array = Array.new %>
      <% @lecture.reviews.each do |review| %>
        <% if review.lecture_id == @lecture[:id]%>
          <% @user = User.find(review.person_reviewed_id) %>
          <% if not user_array.include?(@user) %>
            <h5><%= link_to @user.name, review %></h5>
            <% user_array.push(@user) %>
          <% end %>
        <% end %>
      <% end %>
    </ul>
  </div>
<% else %>
  <h4> Lecture has no reviews! </h4>
<% end %>

app/views/reviews/edit.html.erb
<%= form_for Review.new, url: {action: "update"} do |p| %>
Class: <%= @review.lecture_name %> <%= p.hidden_field :lecture_name, :value => @review.lecture_id %>
Classmate: <%= @review.person_being_reviewed %>  <%= p.hidden_field :person_being_reviewed, :value => @review.person_reviewed_id %>
Rating:      <%= p.number_field :rating , :value => @review.rating%>
Description: <%= p.text_field :description, :value => @review.description %>
<%= p.button "Create" %>
<% end %>

app/views/reviews/new.html.erb
<% @user_array = Array.new %>
<% @users.each do |user| %>
  <% @user_array.push(user.name) %>
<% end %>

<% @lecture_array = Array.new %>
<% @lectures.each do |lecture| %>
  <% @lecture_array.push(lecture.display_name) %>
<% end %>

<div class='container'>
  <h1 class='text-center'>Write a Review!</h1>
  <br>
  <div class='row'>
    <div class='col-md-3'></div>
    <div class='col-md-6'>
      <%= simple_form_for(Review.new, url: {action: "create"}) do |r| %>
        <%= r.input :lecture_name, collection: @lecture_array %>
        <%= r.input :person_being_reviewed, collection: @user_array %>
        <%= r.input :rating, collection: 1..5 %>
        <%= r.input :description, as: :text %>
        <%= r.button :submit %>
      <% end %>
    </div>
    <div class='col-md-3'></div>
  </div>
</div>

app/views/reviews/show.html.erb
<h2><%="Student: " + @person_being_reviewed.name if @person_being_reviewed.name%></h2>
<h4><%="Reviewed by: " + @reviewer.name if @reviewer.name%></h4>
<h5><%="Rating: " + @review.rating.to_s %></h5>
<h3><%="Description: " + @review.description %></h3>

<% if @reviewer.id == current_user[:id] %>
  <h5><%= link_to "Edit this review", edit_review_path %></h5>
<% end %>

<h5><%= link_to "Back to Class", lecture_path(:id => @review.lecture_id) %></h5>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <!-- Example row of columns -->
  <div class="row">
  <% @users.each do |user| %>
    <div class="col-md-4">
      <h2><%= user.name %></h2>
      <p><a class="btn btn-default" href= "/users/<%= user.id %>" role="button">View details &raquo;</a></p>
    </div>
    <% end %>
  </div>
</div> <!-- /container -->

app/views/users/show.html.erb
<div class="container">
<p><h2><%= @user.name + ' '%></h2></p>
<p><%= mail_to @user.email if @user.email %></p>
<h3>Average Rating: <b><%= @average_rating %></b></h3>
<% if @average_given_rating.length > 0 %>
<p>Average rating given: <b><%= @average_given_rating %> </b></p>
<% end %>
<p></p>
<br/>
<table class="table table-hover">
<tr>
<th>Description</th>
<th>Rating</th>
<th>Reviewer</th>
</tr>
<% @user.received_reviews.each do |review| %>
<tr>
<td><%= review.description %></td>
<td><%= review.rating.to_s %></td>
<td><%= link_to review.reviewer.name, users_path + "/" + review.reviewer.id.to_s %></td>
</tr>
<% end %>
</table>
</div>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>